
export default appliedPowerUps = {
    curHealth: { isSet: false, value: 1 },
    totalHealth: { isSet: false, value: 1 },
    maxNumJumps: { isSet: false, value: 1 },
    moveSpeed: { isSet: false, value: 1 },
    shootTime: { isSet: false, value: 1 },
    defense: { isSet: false, value: 1 },
    earningsMultiplier: { isSet: false, value: 1 },
    earnings: { isSet: false, value: 1 },
    plusHealthLevel: { isSet: false, value: 1 },
    plusHealthKill: { isSet: false, value: 1 },
    sizeX: { isSet: false, value: 1 },
    sizeY: { isSet: false, value: 1 },
    size: { isSet: false, value: 1 },
    piercingShot: { isSet: false, value: 1 },
    bulletWidth: { isSet: false, value: 1 },
    numBullets: { isSet: false, value: 1 },
    spreadBullets: { isSet: false, value: 1 },
    numSpreadBullets: { isSet: false, value: 1 },
    homing: { isSet: false, value: 1 },
    hasHomingTime: { isSet: false, value: 1 },
    HomingTime: { isSet: false, value: 1 },
    homingDeltaAngle: { isSet: false, value: 1 },
    perfectHoming: { isSet: false, value: 1 },
    numBounces: { isSet: false, value: 1 },
    bulletSpeed: { isSet: false, value: 1 },
    damage: { isSet: false, value: 1 },
}